# Generated by Django 3.0.8 on 2020-07-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0003_auto_20200725_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='description',
            field=models.CharField(default='Its a thing', max_length=256),
        ),
    ]
