# Generated by Django 3.0.8 on 2020-07-20 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='published',
        ),
    ]
