# Generated by Django 3.0.8 on 2020-07-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='location',
            field=models.CharField(default='', max_length=70),
        ),
    ]
