# Generated by Django 3.0.8 on 2020-07-25 22:08

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0002_npc_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='dialogue',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), size=None),
        ),
    ]
